/**
 * The Operator class represents a relational operator, which can be used to manipulate and process tuples.
 */

package ed.inf.adbs.minibase.operator;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public abstract class Operator {
     // A list of variable names used in this operator.
    protected List<String> varsName = new ArrayList<>();

    /**
     * Dumps the tuples generated by this operator to a file or standard output.
     *
     * @param outputFile the file name to output the tuples to. If outputFile is null or empty, the tuples will be output to standard output.
     */
    public void dump(String outputFile) {
        try {
            PrintWriter writer = null;
            if (outputFile != null && !outputFile.equals("")) {
                writer = new PrintWriter(outputFile);
            }

            boolean isFirstLine = true;
            Tuple nextTuple = this.getNextTuple();
            while (nextTuple != null) {
                if (isFirstLine) {
                    assert writer != null;
                    writer.print(nextTuple);
                    isFirstLine = false;
                } else {
                    writer.print("\n" + nextTuple);
                }
                nextTuple = this.getNextTuple();
            }
            if (writer!=null)
                writer.close();

        } catch (Exception e) {
            System.err.println("Exception occurred during dump operation");
            e.printStackTrace();
        }
    }

    /**
     * Resets this operator to its initial state.
     */
    public abstract void reset();

    /**
     * Retrieves the next tuple generated by this operator.
     *
     * @return the next tuple, or null if there are no more tuples
     */
    public abstract Tuple getNextTuple();

    /**
     * Returns the list of variable names used in this operator.
     *
     * @return a list of variable names
     */
    public List<String> getVarsName() {
        return this.varsName;
    }
}
